name: build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  workflow_dispatch:

jobs:

  build:
    name: build site documentation

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: install antora
      run: npm i @antora/cli@2.3 @antora/site-generator-default@2.3

    - name: run antora
      run: ./node_modules/@antora/cli/bin/antora antora-playbook.yml

    - name: check changes
      run: git status

